INSERT INTO `bairro` VALUES (1, 'Alto da Boa Vista', 1);
INSERT INTO `bairro` VALUES (2, 'Cidade Nova', 1);
INSERT INTO `bairro` VALUES (3, 'Grajaú', 1);
INSERT INTO `bairro` VALUES (4, 'Mangueira', 1);
INSERT INTO `bairro` VALUES (5, 'São Cristóvão', 1);
INSERT INTO `bairro` VALUES (6, 'Andaraí', 1);
INSERT INTO `bairro` VALUES (7, 'Copacabana', 1);
INSERT INTO `bairro` VALUES (8, 'Humaitá', 1);
INSERT INTO `bairro` VALUES (9, 'Maracanã', 1);
INSERT INTO `bairro` VALUES (10, 'Saúde', 1);
INSERT INTO `bairro` VALUES (11, 'Benfica', 1);
INSERT INTO `bairro` VALUES (12, 'Cosme Velho ', 1);
INSERT INTO `bairro` VALUES (13, 'Ipanema', 1);
INSERT INTO `bairro` VALUES (14, 'Praça da Bandeira', 1);
INSERT INTO `bairro` VALUES (15, 'Tijuca', 1);
INSERT INTO `bairro` VALUES (16, 'Botafogo', 1);
INSERT INTO `bairro` VALUES (17, 'Estácio', 1);
INSERT INTO `bairro` VALUES (18, 'Jardim Botânico', 1);
INSERT INTO `bairro` VALUES (19, 'Rio Comprido', 1);
INSERT INTO `bairro` VALUES (20, 'Urca', 1);
INSERT INTO `bairro` VALUES (21, 'Caju', 1);
INSERT INTO `bairro` VALUES (22, 'Flamengo', 1);
INSERT INTO `bairro` VALUES (23, 'Lagoa', 1);
INSERT INTO `bairro` VALUES (24, 'Rocinha', 1);
INSERT INTO `bairro` VALUES (25, 'Vasco da Gama', 1);
INSERT INTO `bairro` VALUES (26, 'Catete', 1);
INSERT INTO `bairro` VALUES (27, 'Gamboa', 1);
INSERT INTO `bairro` VALUES (28, 'Laranjeiras', 1);
INSERT INTO `bairro` VALUES (29, 'Santa Teresa', 1);
INSERT INTO `bairro` VALUES (30, 'Vidigal', 1);
INSERT INTO `bairro` VALUES (31, 'Catumbi', 1);
INSERT INTO `bairro` VALUES (32, 'Gávea', 1);
INSERT INTO `bairro` VALUES (33, 'Leblon', 1);
INSERT INTO `bairro` VALUES (34, 'Santo Cristo', 1);
INSERT INTO `bairro` VALUES (35, 'Vila Isabel', 1);
INSERT INTO `bairro` VALUES (36, 'Centro', 1);
INSERT INTO `bairro` VALUES (37, 'Glória', 1);
INSERT INTO `bairro` VALUES (38, 'Leme', 1);
INSERT INTO `bairro` VALUES (39, 'São Conrado', 1);
INSERT INTO `bairro` VALUES (40, 'Abolição', 1);
INSERT INTO `bairro` VALUES (41, 'Cacuia', 1);
INSERT INTO `bairro` VALUES (42, 'Cordovil', 1);
INSERT INTO `bairro` VALUES (43, 'Galeão', 1);
INSERT INTO `bairro` VALUES (44, 'Jardim Guanabara', 1);
INSERT INTO `bairro` VALUES (45, 'Acari', 1);
INSERT INTO `bairro` VALUES (46, 'Campinho', 1);
INSERT INTO `bairro` VALUES (47, 'Costa Barros', 1);
INSERT INTO `bairro` VALUES (48, 'Guadalupe', 1);
INSERT INTO `bairro` VALUES (49, 'Jardim Sulacap', 1);
INSERT INTO `bairro` VALUES (50, 'Água Santa', 1);
INSERT INTO `bairro` VALUES (51, 'Campo dos Afonsos', 1);
INSERT INTO `bairro` VALUES (52, 'Del Castilho', 1);
INSERT INTO `bairro` VALUES (53, 'Higienópolis', 1);
INSERT INTO `bairro` VALUES (54, 'Lins de Vasconcelos', 1);
INSERT INTO `bairro` VALUES (55, 'Anchieta', 1);
INSERT INTO `bairro` VALUES (56, 'Cascadura', 1);
INSERT INTO `bairro` VALUES (57, 'Deodoro', 1);
INSERT INTO `bairro` VALUES (58, 'Honório Gurgel', 1);
INSERT INTO `bairro` VALUES (59, 'Madureira', 1);
INSERT INTO `bairro` VALUES (60, 'Bancários', 1);
INSERT INTO `bairro` VALUES (61, 'Cavalcanti', 1);
INSERT INTO `bairro` VALUES (62, 'Encantado', 1);
INSERT INTO `bairro` VALUES (63, 'Inhaúma', 1);
INSERT INTO `bairro` VALUES (64, 'Magalhães Bastos', 1);
INSERT INTO `bairro` VALUES (65, 'Barros Filho', 1);
INSERT INTO `bairro` VALUES (66, 'Cidade Universitária', 1);
INSERT INTO `bairro` VALUES (67, 'Engenheiro Leal', 1);
INSERT INTO `bairro` VALUES (68, 'Irajá', 1);
INSERT INTO `bairro` VALUES (69, 'Manguinhos', 1);
INSERT INTO `bairro` VALUES (70, 'Bento Ribeiro', 1);
INSERT INTO `bairro` VALUES (71, 'Cocotá', 1);
INSERT INTO `bairro` VALUES (72, 'Engenho da Rainha', 1);
INSERT INTO `bairro` VALUES (73, 'Jacaré', 1);
INSERT INTO `bairro` VALUES (74, 'Maré', 1);
INSERT INTO `bairro` VALUES (75, 'Bonsucesso', 1);
INSERT INTO `bairro` VALUES (76, 'Coelho Neto', 1);
INSERT INTO `bairro` VALUES (77, 'Engenho de Dentro', 1);
INSERT INTO `bairro` VALUES (78, 'Jacarezinho', 1);
INSERT INTO `bairro` VALUES (79, 'Marechal Hermes', 1);
INSERT INTO `bairro` VALUES (80, 'Brás de Pina', 1);
INSERT INTO `bairro` VALUES (81, 'Colégio', 1);
INSERT INTO `bairro` VALUES (82, 'Engenho Novo', 1);
INSERT INTO `bairro` VALUES (83, 'Jardim América', 1);
INSERT INTO `bairro` VALUES (84, 'Maria da Graça', 1);
INSERT INTO `bairro` VALUES (85, 'Cachambi', 1);
INSERT INTO `bairro` VALUES (86, 'Complexo do Alemão', 1);
INSERT INTO `bairro` VALUES (87, 'Freguesia', 1);
INSERT INTO `bairro` VALUES (88, 'Ilha do Governador', 1);
INSERT INTO `bairro` VALUES (89, 'Jardim Carioca', 1);
INSERT INTO `bairro` VALUES (90, 'Méier', 1);
