INSERT INTO `vaga` VALUES (1, '1', 'Livre', 'Normal', 1);
INSERT INTO `vaga` VALUES (2, '2', 'Livre', 'Normal', 1);
INSERT INTO `vaga` VALUES (3, '3', 'Livre', 'Normal', 1);
INSERT INTO `vaga` VALUES (4, '4', 'Livre', 'Normal', 1);
INSERT INTO `vaga` VALUES (5, '5', 'Livre', 'Normal', 1);
INSERT INTO `vaga` VALUES (6, '6', 'Livre', 'Normal', 1);
INSERT INTO `vaga` VALUES (7, '7', 'Livre', 'Idoso', 1);
INSERT INTO `vaga` VALUES (8, '8', 'Livre', 'Idoso', 2);
INSERT INTO `vaga` VALUES (9, '9', 'Livre', 'Normal', 2);
INSERT INTO `vaga` VALUES (10, '10', 'Livre', 'Normal', 2);
INSERT INTO `vaga` VALUES (11, '11', 'Livre', 'Normal', 2);
INSERT INTO `vaga` VALUES (12, '12', 'Livre', 'Normal', 2);
INSERT INTO `vaga` VALUES (13, '13', 'Livre', 'Idoso', 2);
INSERT INTO `vaga` VALUES (14, '14', 'Livre', ' CPD', 3);
INSERT INTO `vaga` VALUES (15, '15', 'Livre', ' CPD', 3);
INSERT INTO `vaga` VALUES (16, '16', 'Livre', 'Normal', 3);
INSERT INTO `vaga` VALUES (17, '17', 'Livre', 'Normal', 3);
INSERT INTO `vaga` VALUES (18, '18', 'Livre', 'Normal', 3);
INSERT INTO `vaga` VALUES (19, '19', 'Livre', 'Normal', 3);
